global:
  image: clojure:latest

  trigger:
    branch:
      - "*"

  environment:
    # Specify that apt will be used in noninteractive env.
    # https://www.debian.org/releases/sarge/s390/ch05s02.html.en
    DEBIAN_FRONTEND: noninteractive

jobs:
  - name: install and build container

    commands:

      # Update apt in order to download deps for installing clj-kondo
      - apt-get update
      - apt-get install unzip

      # Intall clj-kondo
      - curl -sLO https://raw.githubusercontent.com/clj-kondo/clj-kondo/master/script/install-clj-kondo
      - chmod +x install-clj-kondo
      - ./install-clj-kondo
      - clj-kondo --lint src --dependencies --parallel --copy-configs

      # run clojure
      - touch hello.clj
      - echo '(println "Hello World")' >> hello.clj
      - echo "(println (+ 1 2 3 4 5))" >> hello.clj
      - clj hello.clj
